### ISSUE TITLE
Sensor combined with wemos d1 mini pro

### ISSUE THREAD

**Issue by riochicken** [SFeli/ESP32_CJMCU-8128#2]
Hi,

Did anybody try to connect the CJMCU-8128 with a wemos d1 mini pro?

I've uploaded the code from this project to the device and that sort of works but in the serial monitor I get some stange readings and I have to set the serial monitor to 115200, when set to 9600, it shows a lot of jiberish. The only thing it shows in delays is:

load 0x4010f000, len 1392, room 16 
tail 0
chksum 0xd0
csum 0xd0
v3d128e5c
~ld
v⸮⸮⸮

btw, when set to 9600 it shows: ⸮!⸮L⸮<1⸮1⸮⸮⸮

No real measurements  as output and stated in the code.

Anybody any idea? Any help would be appriciated!

Kind regards

Richard

**Comment by SFeli** [comment]
Hello Richard,
with some delay I found your issue. 
You are right the reduction of the serial monitor is useless and confuse. So I commented out the line.
For your purpose I suggest that you change the PIN to the corresponding I2 C Wemos
I think it's D1 and D2 but I'm not sure. - It's on the line Wire.Begin(D1,D2) instead of wire.begin(21,22)

Hope you can follow and close the issue. 
Regards
stefan

**Comment by SFeli** [comment]
Hope you are fine
